################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################

@endpoint = http://localhost:{{$dotenv PORT}}/api

### 404
GET {{ endpoint }}/test404


####################################################################################################
#                                              FAMILY                                              #
####################################################################################################

### List of all families
GET {{ endpoint }}/family

### Create a wrong name family  -->  error
POST {{ endpoint }}/family
content-type: application/json

{
  "name": "new Family"
}

### Create a new family
POST {{ endpoint }}/family
content-type: application/json

{
  "name": "New Family"
}

### Failed update one family  -->  error
PATCH {{ endpoint }}/family/1
content-type: application/json

{
  "name": "New pokémon"
}

### Update one family
PATCH {{ endpoint }}/family/1
content-type: application/json

{
  "name": "New Pokémons"
}

### Delete a family by its id
DELETE {{ endpoint }}/family/6



####################################################################################################
#                                             CAPACITY                                             #
####################################################################################################

### List of all capacities
GET {{ endpoint }}/capacity

### Create a wrong name capacity  -->  error
POST {{ endpoint }}/capacity
content-type: application/json

{
  "name": "magie"
}

### Create an already existed capacity  -->  error
POST {{ endpoint }}/capacity
content-type: application/json

{
  "name": "Force"
}

### Create a new capacity
POST {{ endpoint }}/capacity
content-type: application/json

{
  "name": "Magie"
}

### Failed update one family  -->  error
PATCH {{ endpoint }}/capacity/4
content-type: application/json

{
  "name": "Magie et Puissance"
}

### Update one capacity name
PATCH {{ endpoint }}/capacity/2
content-type: application/json

{
  "name": "Magie Et Puissance"
}

### Update one capacity description
PATCH {{ endpoint }}/capacity/2
content-type: application/json

{
  "description": "La magie apporte une grande puissance au combat pour ganer"
}

### Delete a family by its id
DELETE {{ endpoint }}/capacity/5



####################################################################################################
#                                            CHARACTER                                             #
####################################################################################################

### List of all characters in one family
GET {{ endpoint }}/character/family/2

### Get one character by its id
GET {{ endpoint }}/character/6

### Create a wrong name character  -->  error
POST {{ endpoint }}/character/family/2
content-type: application/json

{
  "name": "Schtroumpf bricoleur"
}

### Create a character with missing family_id  -->  error
POST {{ endpoint }}/character/family/2
content-type: application/json

{
  "name": "Schtroumpf Bricoleur"
}

### Create a character in the wrong family params.familyId !== body.family_id  -->  error
POST {{ endpoint }}/character/family/2
content-type: application/json

{
  "name": "Schtroumpf Bricoleur",
  "family_id": "1"
}

### Create a character without picture in a family
POST {{ endpoint }}/character/family/2
content-type: application/json

{
  "name": "Schtroumpf Bricoleur",
  "family_id": "2"
}

### Create a character with a picture in a family
POST {{ endpoint }}/character/family/2
content-type: application/json

{
  "name": "Schtroumpf Bricoleur",
  "picture": "test",
  "family_id": "2"
}

### Update a character with a wrong name format  -->  error
PATCH {{ endpoint }}/character/7
content-type: application/json

{
  "name": "Schtroumpf bricoleur"
}

### Update a character name
PATCH {{ endpoint }}/character/7
content-type: application/json

{
  "name": "Schtroumpf Bricoleur"
}

### Update a character picture
PATCH {{ endpoint }}/character/7
content-type: application/json

{
  "picture": "test"
}

### Update a character in changing his family
PATCH {{ endpoint }}/character/7
content-type: application/json

{
  "family_id": 1
}

### Update a character
PATCH {{ endpoint }}/character/7
content-type: application/json

{
  "name": "Schtroumpf Coquet",
  "picture": "/",
  "family_id": 2
}

### Delete a character
DELETE {{ endpoint }}/character/7



####################################################################################################
#                                             BATTLE                                               #
####################################################################################################

### List all battles with all players into them
GET {{ endpoint }}/battle/

### List battles into where the user is part of players
GET {{ endpoint }}/battle/?playing=yes

### List battles into where the user is not part of players
GET {{ endpoint }}/battle/?playing=no
