################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################

@endpoint = http://localhost:{{$dotenv PORT}}/api

### 404
GET {{ endpoint }}/test404


#########################
#         FAMILY         #
#########################

### List of families
GET {{ endpoint }}/family

### Create a wrong name family  -->  error
POST {{ endpoint }}/family
content-type: application/json

{
  "name": "new Family"
}

### Create a new family
POST {{ endpoint }}/family
content-type: application/json

{
  "name": "New Family"
}